// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using web_apiproductdocker.Persistencia;

namespace web_apiproductdocker.Migrations
{
    [DbContext(typeof(ContextoDocker))]
    [Migration("20230507020458_Product")]
    partial class Product
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("web_apiproductdocker.Modelo.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<double>("Cantidadreorden")
                        .HasColumnType("double precision");

                    b.Property<int>("Codfamilia")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("Codigobarraprincipal")
                        .HasColumnType("text");

                    b.Property<int>("Codimpuesto")
                        .HasColumnType("integer");

                    b.Property<int>("Codmarca")
                        .HasColumnType("integer");

                    b.Property<long>("Codnegocio")
                        .HasColumnType("bigint");

                    b.Property<int>("Codtipoproducto")
                        .HasColumnType("integer");

                    b.Property<int>("Codunidadmedida")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<double>("Costounitario")
                        .HasColumnType("double precision");

                    b.Property<string>("Descripcionlarga")
                        .HasColumnType("text");

                    b.Property<bool>("Escompuesto")
                        .HasColumnType("boolean");

                    b.Property<string>("Esimpoconsumo")
                        .HasColumnType("text");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<double>("Iva")
                        .HasColumnType("double precision");

                    b.Property<string>("Ivaincluido")
                        .HasColumnType("text");

                    b.Property<string>("Nomarticulo")
                        .HasColumnType("text");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<double>("Porcentajeimpoconsumo")
                        .HasColumnType("double precision");

                    b.Property<double>("Precioconiva")
                        .HasColumnType("double precision");

                    b.Property<double>("Preciosugerido")
                        .HasColumnType("double precision");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<string>("Serial")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<double>("Stock")
                        .HasColumnType("double precision");

                    b.Property<double>("Stockmaximo")
                        .HasColumnType("double precision");

                    b.Property<double>("Stockminimo")
                        .HasColumnType("double precision");

                    b.Property<double>("Talla")
                        .HasColumnType("double precision");

                    b.Property<string>("Tipoiva")
                        .HasColumnType("text");

                    b.Property<double>("Valorimpoconsumo")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
